FROM node:alpine

WORKDIR '/home/node/app'

COPY --chown=node:node ./package.json ./
RUN npm install
#COPY --chown=node:node ./ ./
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]
